/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d3daea",
        "on-secondary-fixed": "#002117",
        "tertiary": "#55615a",
        "on-error": "#ffffff",
        "surface-variant": "#dce2f3",
        "on-surface-variant": "#3c4a42",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#3e4943",
        "primary": "#006c49",
        "on-secondary": "#ffffff",
        "on-background": "#151c27",
        "outline": "#6c7a71",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9ff",
        "on-primary-fixed-variant": "#005236",
        "primary-container": "#10b981",
        "on-tertiary-fixed": "#131e19",
        "on-primary-container": "#00422b",
        "primary-fixed-dim": "#4edea3",
        "inverse-primary": "#4edea3",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#95d3ba",
        "surface-container": "#e7eefe",
        "outline-variant": "#bbcabf",
        "surface-container-highest": "#dce2f3",
        "surface-container-high": "#e2e8f8",
        "tertiary-fixed": "#d9e6dd",
        "surface-tint": "#006c49",
        "secondary-container": "#adedd3",
        "on-secondary-container": "#306d58",
        "surface": "#f9f9ff",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#99a69e",
        "primary-fixed": "#6ffbbe",
        "on-secondary-fixed-variant": "#0b513d",
        "on-primary-fixed": "#002113",
        "inverse-on-surface": "#ebf1ff",
        "background": "#f9f9ff",
        "tertiary-fixed-dim": "#bdcac1",
        "secondary": "#2b6954",
        "surface-container-low": "#f0f3ff",
        "on-tertiary-container": "#303c36",
        "on-surface": "#151c27",
        "inverse-surface": "#2a313d",
        "secondary-fixed": "#b0f0d6",
        "error": "#ba1a1a"
      },
      spacing: {
        "container-padding": "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "gutter": "16px",
        "section-gap": "48px",
        "unit": "8px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "stats-display": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "h1": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "h3": ["20px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "stats-display": ["28px", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
